### ISSUE TITLE
Unnecessary natbib settings?

### ISSUE THREAD

**Issue by gcapes** [gcapes/latex-thesis-template#8]
@tombishop1 
Are these lines needed?

This one defines a macro that isn't used
https://github.com/gcapes/latex-thesis-template/blob/bibtex/thesis.tex#L22

and this one overrides the default settings for the chosen style - if this isn't a requirement for thesis submission, I might remove it or at least write a comment?
https://github.com/gcapes/latex-thesis-template/blob/bibtex/thesis.tex#L23

**Comment by tombishop1** [comment]
Hmm yes. I inherited those, and have largely moved away from Natbib now. That macro is for a particular citation style (by the look of it, something like "...Smith's (2001) assertion that...". It is probably surplus to requirements, although is of some utility in special cases. I'm guessing the other line is there so as to set a comma to appear between the author name and publication date. For example, I think the default looks like:
(Smith 2001), whereas we are aiming for:
(Smith, 2001).
More detail [here](http://merkel.texture.rocks/Latex/natbib.php). Are these necessary to comply with the University specification? I don't think so - it just has to be consistent. Personally I prefer it.

**Comment by gcapes** [comment]
Ok, great thanks!
